# Generated by Django 5.2 on 2025-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("N", "No Refund"),
                    ("P", "Pending Refund"),
                    ("C", "Refunded"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("S", "Shipped"),
                    ("D", "Delivered"),
                    ("R", "Returned"),
                    ("C", "Cancelled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
