# Generated by Django 5.2.1 on 2025-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_remove_category_description_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
