# Generated by Django 5.2.1 on 2025-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
